baseurl = "/"
languageCode = "en-us"
title = "Hexagon Bio"
sectionPagesMenu = "main"

[menu]
	[[menu.main]]
	identifier = "about"
	name = "ABOUT"
	url = "/about"
	weight = 1

	[[menu.main]]
	identifier = "news"
	name = "NEWS"
	url = "/news"
	weight = 2

	[[menu.main]]
	identifier = "publications"
	name = "PUBLICATIONS"
	url = "/publications"
	weight = 3

	[[menu.main]]
	identifier = "team"
	name = "TEAM"
	url = "/team"
	weight = 4

	[[menu.main]]
	identifier = "jobs"
	name = "JOBS"
	url = "/jobs"
	weight = 5

	[[menu.main]]
	identifier = "contact"
	name = "CONTACT"
	url = "/contact"
	weight = 6
